/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1dpbo2022;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class AuthorForm extends javax.swing.JFrame {
    dbConnection db = new dbConnection();
    /**
     * Creates new form AuthorForm
     */
    public AuthorForm() {
        initComponents();
    }
    
    private void clearForm() {
        inputName.setText("");
        inputCountBook.setText("");
        inputImg.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorTitle = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        countBookLabel = new javax.swing.JLabel();
        inputCountBook = new javax.swing.JTextField();
        inputImg = new javax.swing.JTextField();
        imgLabel = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        authorTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        authorTitle.setText("Add Author");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabel.setText("Nama");

        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        countBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        countBookLabel.setText("Jumlah Buku");

        inputCountBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCountBookActionPerformed(evt);
            }
        });

        inputImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputImgActionPerformed(evt);
            }
        });

        imgLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgLabel.setText("URL Gambar");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 166, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countBookLabel)
                                    .addComponent(nameLabel)
                                    .addComponent(imgLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputCountBook, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(inputName)
                                    .addComponent(inputImg)))
                            .addComponent(authorTitle))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countBookLabel)
                    .addComponent(inputCountBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgLabel)
                    .addComponent(inputImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBtn)
                    .addComponent(clearBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputCountBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCountBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCountBookActionPerformed

    private void inputImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputImgActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String nama = inputName.getText();
        String jumlah_buku_Str = inputCountBook.getText();
        String urlImg = inputImg.getText();
        
        if (nama.length() == 0 || jumlah_buku_Str.length() == 0 || urlImg.length() == 0) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        }else {
            Author dataAuthor = new Author();
            dataAuthor.setImg(urlImg);
            dataAuthor.setNama(nama);
            int jumlah_buku = Integer.parseInt(jumlah_buku_Str);
            dataAuthor.setJumlahBuku(jumlah_buku);
            
            try {
                String sql = "INSERT INTO `tauthors` (`id`, `img`, `nama`, `jumlah_buku`) VALUES (null, '"+dataAuthor.getImg()+"', '"+dataAuthor.getNama()+"',"+dataAuthor.getJumlahBuku()+");";
                db.Query(sql);
            }catch(Exception e) {
                System.err.println("Insert gagal " +e.getMessage());
            }
            clearForm();
        }
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorTitle;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel countBookLabel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JTextField inputCountBook;
    private javax.swing.JTextField inputImg;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
